sudo: required
dist: trusty

language: cpp

compiler:
    - gcc

env:
  - USE_GCC7=0
  - USE_GCC7=1


before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - if [ "$USE_GCC7" = "1" ]; then sudo apt-get install -y -qq g++-7; export CXX="g++-7" CC="gcc-7"; fi
  - $CXX --version
  - sudo apt-get install --allow-unauthenticated -y build-essential libc6-x32 g++-multilib

script:
  - $CXX --version
  - make
